### ISSUE TITLE
Mobile / home mal proportionnée

### ISSUE THREAD

**Issue by bgantaume** [agilidee/agilidee.com#3]
![unnamed](https://cloud.githubusercontent.com/assets/1662023/6616621/1f610f70-c8b0-11e4-9b38-53fe2caa96d3.jpg)

**Comment by BenoitMC** [comment]
Problème résolu en mode portrait mais pas en paysage.

**Comment by BenoitMC** [comment]
Plus de problème avec mon mobile ni en portrait ni en paysage.
